package Assignment_5Q2;

import static org.junit.Assert.*;

import org.junit.*;
public class CalculatorTest {
	
	@Test
	public void test() {
		Calculator cal=new Calculator();
		assertEquals(9,cal.add(4, 5));
		assertEquals(7,cal.subtract(14, 7));
		assertEquals(5,cal.divide(25, 0));
		assertEquals(45,cal.multiply(9, 5));
	}
	@Test
	public void whenExceptionThrown_thenAssertionSucceeds() {
	    Exception exception = assertThrows(ArithmeticException.class, () -> {
	        Integer.parseInt("1a");
	    });

	    String expectedMessage = "Divide By Zero";
	    String actualMessage = exception.getMessage();

	    assertTrue(actualMessage.contains(expectedMessage));
	}

}
